# config/packages/fos_user.yaml
fos_user:
  #resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "oumarsow92bbsy@gmail.com"
    sender_name: "oumarsow92bbsy@gmail.com"